name: benchscofi release

on:
  release:
    types: [published]

jobs:
  pypi-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: sed -i "s:9999:${VERSION//*v/}:" setup.py conda/meta.yaml
      env:
          VERSION: ${{ github.ref }}
    - uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python setup.py sdist bdist_wheel
        twine upload dist/*
  conda-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.5
    - run: sed -i "s:9999:${VERSION//*v/}:" setup.py conda/meta.yaml
      env:
          VERSION: ${{ github.ref }}
    - uses: s-weigand/setup-conda@v1
    - name: prepare
      run: |
        python setup.py sdist bdist_wheel
        conda install -y anaconda-client conda-build conda-verify
        conda update conda -y
        conda config --set channel_priority strict
        conda config --set anaconda_upload yes
        conda config --add channels conda-forge
    - name: build
      run: |
        cd conda/
        conda build --user recess --token $ANACONDA_TOKEN .
      env:
        ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}